services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Helhum\Topwire\:
        resource: '../Classes/*'

    Helhum\Topwire\Fluid\Parser\TopwireContextParser:
        public: true

    Helhum\Topwire\Middleware\TopwireContextResolver:
        arguments:
            $cache: '@cache.pages'
