services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Topwire\:
        resource: '../Classes/*'

    Topwire\Fluid\Parser\TopwireContextParser:
        public: true

    Topwire\Middleware\TopwireContextResolver:
        arguments:
            $cache: '@cache.pages'

    Topwire\ContentObject\TopwireContentObject:
        tags:
            - name: 'frontend.contentobject'
              identifier: 'TOPWIRE'

    Topwire\Typolink\TopwirePageLinkModifier:
        tags:
            - name: 'event.listener'
              method: 'modifyQueryParameters'
              identifier: 'TopwirePageLinkModifier'
